In [1]:
# Phutharesuan Wachirapisut
# 651610348
# Lab01_01
# 229323 sec 002

import numpy as np

dimen = int(input("Enter dimension of matrix: "))
data_a = np.random.randint(1,9,size=dimen*dimen)
arr_a = data_a.reshape(dimen,dimen) # ทำให้เป็น array2D

print(arr_a)
print(type(arr_a))

[[5 6 6 1 7]
 [7 3 4 1 5]
 [2 7 3 5 1]
 [8 5 8 7 7]
 [6 6 4 4 4]]
<class 'numpy.ndarray'>


In [2]:
sum_row = arr_a.sum(axis=0);sum_row

array([28, 27, 25, 18, 24])

In [3]:
sum_col = arr_a.sum(axis=1);sum_col

array([25, 20, 18, 35, 24])

In [4]:
a_diagonal = 0
b_diagonal = 0
for item in range(len(arr_a)):
  a_diagonal += arr_a[item][item]
  b_diagonal += arr_a[item][len(arr_a)-item-1]
  # print(arr_a[item][item])
  # print(arr_a[item][len(arr_a)-item-1])

sum_diagonal = a_diagonal, b_diagonal;sum_diagonal


(np.int64(22), np.int64(22))

In [5]:
sum_total = arr_a.flatten().sum(axis=0);sum_total

np.int64(122)

In [6]:
result = arr_a + arr_a.transpose();result

array([[10, 13,  8,  9, 13],
       [13,  6, 11,  6, 11],
       [ 8, 11,  6, 13,  5],
       [ 9,  6, 13, 14, 11],
       [13, 11,  5, 11,  8]])