In [1]:
# Phutharesuan Wachirapisut
# 651610348
# Lab01_02
# 229323 sec 002

import numpy as np

dimen_a = int(input("Enter number of row of matrix A: "))
dimen_b = int(input("Enter number of column of matrix A: "))
data_a = np.random.randint(1,9,size=dimen_a*dimen_b)
arr_a = data_a.reshape(dimen_a, dimen_b)

dimen_m = int(input("Enter number of row of matrix B: "))
dimen_n = int(input("Enter number of column of matrix B: "))
data_b = np.random.randint(1,9,size=dimen_m*dimen_n)
arr_b = data_b.reshape(dimen_m, dimen_n)

print("Metrix A:\n{}".format(arr_a))
print("Metrix B:\n{}".format(arr_b))

Metrix A:
[[5 6 1]
 [1 3 2]]
Metrix B:
[[1 5]
 [1 4]
 [3 8]]


In [2]:
if (dimen_a,dimen_b) != (dimen_m,dimen_n):
  print("This calculation is wrong.")
else:
  add_metrix = arr_a + arr_b
  print("ผลบวกเมทริกซ์:\n{}".format(add_metrix))

This calculation is wrong.


In [3]:

if (dimen_a,dimen_b) != (dimen_n,dimen_m):
  print("This calculation is wrong.")
else:
  multi_metrix = np.ones([dimen_a,dimen_n],dtype='i')
  for row in range(dimen_a):
    for column in range(dimen_n):
      a = 0
      for i in range(0,dimen_a+1):
        a += arr_a[row][i] * arr_b[i][column]
        multi_metrix[row][column] = a

  print("ผลคูณของเมตริกซ์:\n{}".format(multi_metrix))


ผลคูณของเมตริกซ์:
[[14 57]
 [10 33]]


In [4]:
k = int(input("Enter integer: "))
print("ผลคูณของเมตริกซ์กับจำนวนเต็ม:\n{}".format(k*arr_a))

ผลคูณของเมตริกซ์กับจำนวนเต็ม:
[[50 60 10]
 [10 30 20]]
