In [3]:
# Phutharesuan Wachirapisut
# 651610348
# Lab01_03
# 229323 sec 002
import numpy as np
import string 

string_a = str(input("Enter string: ")).lower().strip()
lowletters = list(string.ascii_lowercase)

print(string_a)
print(isinstance(string_a,str))

nxinfvisuosovnneereieeiueefnsoeoornnrnrizsnisfnveiifoivrwoioenooswengohvsnotenierxeuuresvinusfineernnfetreseoenienfxufnozseiietwwnnoxvfhnuesovzrvxeeoifeoefvreoevoxfnuiutnvetereehongtiuuitfieenoetrxffveorneoetfreerhnvteezieiefvfvsoifvnsoeiteoosriewrefoinvtsiuroofeueeerrhrueeseetehurfivowieiiietfhofxoovzovfgissweesxfneitenrfnhginzerxvnne
True


In [4]:
indstr_a = [] # index string_a
for item in string_a:
    indstr_a.append(lowletters.index(item))

list_a = ["zero",'one','two','three','four','five','six','seven','eight','nine']

matrix_a = np.zeros([26,10],dtype='float32')

for column in range(10):
    for j in list_a[column]:
        matrix_a[lowletters.index(j),column] += 1

matrix_a


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 2., 0., 1., 0., 2., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 2.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 

In [5]:
matrix_b = np.zeros([26,1],dtype="float32")
    
for j in indstr_a:
    matrix_b[j, 0] += 1
    
matrix_b

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [68.],
       [27.],
       [ 4.],
       [ 8.],
       [36.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [38.],
       [36.],
       [ 0.],
       [ 0.],
       [25.],
       [20.],
       [15.],
       [15.],
       [22.],
       [ 7.],
       [10.],
       [ 0.],
       [ 6.]], dtype=float32)

In [6]:
result = np.linalg.lstsq(matrix_a, matrix_b) ;result

(array([[ 6.],
        [ 8.],
        [ 7.],
        [ 4.],
        [15.],
        [12.],
        [10.],
        [10.],
        [ 4.],
        [10.]], dtype=float32),
 array([3.3918253e-29], dtype=float32),
 np.int32(10),
 array([4.477262 , 2.632956 , 2.30554  , 1.9744008, 1.8483384, 1.5047852,
        1.4069062, 1.0902799, 0.8106197, 0.5495108], dtype=float32))