# ให้นักศึกษาทำการเขียนโปรแกรมคำสั่ง เพื่อให้เกิดผลลัพธ์ตามที่แสดงใน output โดยสามารถเขียนคำสั่งมากกว่า 1 คำสั่ง

In [1]:
# Phutharesuan Wachirapisut
# 651610348
# Lab01_01
# 229323 sec 002
import numpy as np

## 1. สร้าง ndarray ชื่อ array_a จาก list ให้มีขนาด 2 มิติ



In [2]:
list_a = list(range(1,7))
array_a = np.array(list_a).reshape([2,3])
print(array_a)

[[1 2 3]
 [4 5 6]]


## 2. สร้าง ndarray ชื่อ array_b โดยใช้ ฟังก์ชัน arange

In [3]:
array_b = np.arange(2,14,2).reshape([3,2])

print(array_b)

[[ 2  4]
 [ 6  8]
 [10 12]]


## 3.ให้ทำการแสดงค่าจำนวนคอลัมน์ของ array_a และจำนวนแถวของ array_b

In [4]:
cols = (array_a.shape)[1]
rows = (array_b.shape)[0]

print("column of array_a : {}".format(cols))
print("row of array_b : {}".format(rows))

column of array_a : 3
row of array_b : 3


## 4. ทำการคูณเมทริกซ์ array_a และ เมทริกซ์ array_b แล้วเก็บผลลัพธ์ไว้ที่เมทริกซ์ array_c

In [7]:
array_c = np.dot(array_a,array_b)
print(array_c)

[[ 44  56]
 [ 98 128]]


'\n[[ 44  56]\n [ 98 128]]\n '

## 5.หาค่า determinant ของเมริกซ์ array_c

In [8]:
det_c = np.linalg.det(array_c)
print("Determinant of matrix C : ", det_c)

Determinant of matrix C :  143.99999999999937


## 6.หาค่า inverse ของเมริกซ์ array_c

In [10]:
inv_c = np.linalg.inv(array_c)
print("Inverse matrix c : ", inv_c)

Inverse matrix c :  [[ 0.88888889 -0.38888889]
 [-0.68055556  0.30555556]]


## 7. แสดงค่าของข้อมูลแถวสุดท้ายของ array_a โดยใช้คำสั่งในการหาตำแหน่ง (index) ของแถวสุดท้าย **ห้ามใช้การคีย์ระบุหมายเลขของแถวสุดท้ายเอง**

In [35]:
print(array_a[1::cols].flatten())

[4 5 6]


## 8. แสดงค่า col สุดท้าย ของทุกแถวที่เป็นเลขคู่ของ array_b **ห้ามใช้การคีย์ระบุหมายเลขของคอลัมน์สุดท้าย**

In [42]:
print(array_b[::2,1::2].flatten())

[ 4 12]
