# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:
https://numpy.org/doc/stable/index.html

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### diag
Return a diagonal or construct a diagonal array

In [12]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
np.diag(np.array([1, 2, 3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
np.diag(x)

array([1, 5, 9])

### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
np.linspace(12,10,22)

array([12.        , 11.9047619 , 11.80952381, 11.71428571, 11.61904762,
       11.52380952, 11.42857143, 11.33333333, 11.23809524, 11.14285714,
       11.04761905, 10.95238095, 10.85714286, 10.76190476, 10.66666667,
       10.57142857, 10.47619048, 10.38095238, 10.28571429, 10.19047619,
       10.0952381 , 10.        ])

## eye

Creates an identity matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(2)

array([0.11900213, 0.1637265 ])

In [19]:
np.random.rand(5,5)

array([[0.62864884, 0.59931818, 0.05130443, 0.50634985, 0.01565208],
       [0.39233118, 0.62286663, 0.28157899, 0.44473146, 0.49986225],
       [0.02178935, 0.04335089, 0.06665725, 0.13444497, 0.60781166],
       [0.28366202, 0.76159448, 0.53665375, 0.33903615, 0.0028615 ],
       [0.01062259, 0.67915859, 0.88332193, 0.92755339, 0.65767683]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(2)

array([-0.10171587,  0.68093008])

In [21]:
np.random.randn(5,5)

array([[-0.49681957, -1.12406298, -1.86323362, -0.48262895,  1.00788266],
       [ 0.88805181, -0.15841995, -1.03424396, -0.75392232,  0.40671404],
       [-0.75417669, -0.52636038, -0.02097458,  0.16423775,  1.91723981],
       [-0.46103677, -0.26268462,  0.33651966,  0.03318902,  0.30157617],
       [ 0.04213863,  0.09721971,  0.62763882,  0.92776654, -0.97361834]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

46

In [23]:
np.random.randint(1,100,10)

array([98, 45, 18, 21, 15, 26, 25, 38, 31, 59])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([43, 18, 28, 43, 17,  0, 32, 27, 42, 19])

## Reshape
Returns an array containing the same data with a new shape.

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([43, 18, 28, 43, 17,  0, 32, 27, 42, 19])

In [29]:
ranarr.max()

43

In [30]:
ranarr.argmax()

0

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmin()

5

### sum, mean, std
These are used for computing summarize, mean and standard deviation

In [33]:
ranarr1 = np.random.randint(0,50,10)

In [34]:
ranarr1

array([40,  6, 17, 49, 15, 20, 13, 42, 30, 29])

In [35]:
ranarr1.sum()

261

In [36]:
ranarr1.mean()

26.1

In [37]:
ranarr1.std()

13.46439749858864

## Shape

Shape is an attribute that arrays have (not a method):

In [38]:
# Vector
arr.shape

(25,)

In [39]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [42]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [43]:
arr.dtype

dtype('int64')

## Set Operations

### unique

Select only one value, no duplicate data in same value

In [44]:
arr = np.array([2, 1, 2, 4, 5, 3, 2, 1, 4, 6])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [45]:
names = np.array(['Bob', 'Tom', 'Bill', 'Jane', 'Bob', 'Joe', 'Bob', 'Tom'])
np.unique(names)

array(['Bill', 'Bob', 'Jane', 'Joe', 'Tom'], dtype='<U4')

In [46]:
names = np.array(['Bob', 'Tom', 'Bill', 'Jane', 'Bob', 'Joe', 'Bob', 'Tom'])
sorted(set(names))

['Bill', 'Bob', 'Jane', 'Joe', 'Tom']

### in1d(x, y)
Compute a boolean array indicating whether each element of x is contained in y

In [47]:
arr = np.array([2, 0, 2, 4, 5, 3, 2, 1, 4, 6])
np.in1d(arr, [0,1,5])

array([False,  True, False, False,  True, False, False,  True, False,
       False])

# Great Job!